application: sailfish-consulting
version: 1
runtime: python
api_version: 1

handlers:
- url: /ota/(.*)\.cod
  static_files: media/ota/\1.cod
  upload: media/ota/(.*)\.cod
  mime_type: application/vnd.rim.cod

- url: /ota/(.*)\.jad
  static_files: media/ota/\1.jad
  upload: media/ota/(.*)\.jad
  mime_type: text/vnd.sun.j2me.app-descriptor

- url: /ota/(.*)\.jar
  static_files: media/ota/\1.jar
  upload: media/ota/(.*)\.jar
  mime_type: application/java-archive

- url: /media
  static_dir: media

- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon.ico

- url: /.*
  script: main.py
